In [5]:
# 1
# 데이터 준비: 성적이 담긴 리스트 만들기
scores = [85, 92, 55, 78, 40, 96, 73]

# 통계 계산: 총 학생 수, 최고점, 최저점, 평균 구하기
print('총 학생수: ', len(scores), '명')
print('최고점: ', max(scores), '점')
print('최저점: ', min(scores), '점')
avg = sum(scores) / len(scores)
print(f'평균: {avg:.1f} 점')

# 등급 출력: for문 + if문으로 각 점수의 등급 출력
for score in scores:
    if score >= 90:
        print('점수: ', score, '-> A학점')
    elif score >= 80:
       print('점수: ', score, '-> B학점')
    elif score >= 70:
        print('점수: ', score, '-> C학점')
    elif score >= 60:
        print('점수: ', score, '-> D학점')
    else:
        print('점수: ', score, '-> F학점')

# 정렬, 슬라이싱: 점수를 정렬하고 상위 3개만 뽑기
scores.sort(reverse = True)
print('상위 3개: ', scores[:3])

총 학생수:  7 명
최고점:  96 점
최저점:  40 점
평균: 74.1 점
점수:  85 -> B학점
점수:  92 -> A학점
점수:  55 -> F학점
점수:  78 -> C학점
점수:  40 -> F학점
점수:  96 -> A학점
점수:  73 -> C학점
상위 3개:  [96, 92, 85]


In [6]:
# 2
# 원소가 모두 3인 (3, 4, 5) 형태의 numpy.array를 출력
import numpy as np

arr_my = np.full((3, 4, 5), 3)
print(arr_my)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [7]:
# 3
# numpy.array를 이용하여 패턴 출력 (반복문 사용)
arr = np.zeros((7,7), dtype = int)
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1

for row in range(7):
    for col in range(7):
        print(arr[row, col], end= "")
    print()

0101010
1010101
0101010
1010101
0101010
1010101
0101010
